### ISSUE TITLE
The forum needs a complete retheming

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/OpenUserCSS-DeepDark#12]

**Comment by RaitaroH** [comment]
To do:
+~~in the chat~~
++ ~~fix the svgs: edit, close, maximize (modal aka minimized version)~~
++ ~~add new corespondents~~
++ ~~search in maximized~~

+ groups background image is removed
+ ~~posting comments~~
+~~edit profile social links~~
+ ~~blue button text hover is blue~~
+ ~~did you know panel~~
+ notifications unread background

P.S. I am ~~strikethrough-ing~~ stuff that is done.

**Comment by RaitaroH** [comment]
Yo @tkosamja if you want to take a stab at these. I don't have that much free time.

**Comment by tkosamja** [comment]
Sure, I'll take a look

**Comment by tkosamja** [comment]
Is this the current state of the theme? Just to be sure.
![screenshot from 2018-02-03 12-48-20](https://user-images.githubusercontent.com/26143003/35767239-8e212508-08e0-11e8-8619-10281024ba1a.png)

**Comment by RaitaroH** [comment]
Oh, jee no. Update the theme. 1.2.8
You can take a look at what I have above in that list. If you do want to take a look put some comments around so I know the hell I am looking at. Thx.
![screenshot_20180203_155952](https://user-images.githubusercontent.com/19552720/35767795-45a1c0f6-08fb-11e8-8205-de4e3d149efa.png)

**Comment by tkosamja** [comment]
I installed it from scratch from openusercss.org

**Comment by DecentM** [comment]
@RaitaroH You managed to edit the comment instead of replying :D 

Original:  
@tkosamja I don't update all the time, so make sure you install from github just in case.

**Comment by RaitaroH** [comment]
@DecentM XD Nice. Thank you.
@tkosamja Sorry for that.

**Comment by tkosamja** [comment]
@DecentM I installed it from GitHub and yet it keeps the same way...

**Comment by Mottie** [comment]
Try deleting the style, then reinstalling. Stylus won't update it if you've edited the style locally and pressed the update button a few times on the manage page.

**Comment by tkosamja** [comment]
Yeah I did it. For some reason it's not working, I must be doing something wrong.
Update: Seems to be working

**Comment by RaitaroH** [comment]
@tkosamja The forum is usable. What needs to be fixed is not going to be that big of a deal. You can go around and comment. The chat is oke too.

**Comment by tkosamja** [comment]
I'm fixing it! Looking good so far

**Comment by RaitaroH** [comment]
Nice. Thank you. Just keep going with the comments so I know what you are theming there.

**Comment by tkosamja** [comment]
~~in the chat
++ fix the svgs: edit, close, maximize (modal aka minimized version)
++ add new corespondents
++ search in maximized~~
Everything in the chat is fixed. Well, at least I think. `add new corespondents` was a really small fix

~~edit profile social links~~
I think it's fixed too. If it's not, I guess I fixed another thing LOL.

__notifications unread background__
Did not had any unread notification so coulnd't fix it

__groups background image is removed__
Not sure what was supposed to fix.

@RaitaroH do you want me to make a pull request?

1db04c9fbb3cda082b16e6fbaf40e6d086cadf3b for the final fix
8c4a9f897f6fc542aae256794cd1245f6d253c95 to see changes

**Comment by RaitaroH** [comment]
For notifications:
```
.chat-list li.unread
{
    background-color: var(--second-background) !important;
}
.chat-list li.unread:hover
{
    background-color: var(--hover-background) !important;
}
```

**Comment by RaitaroH** [comment]
On this page:
https://forums.openusercss.org/groups

We need this:
```
.groups.list .list-cover
{
    background-image: url(/assets/images/cover-default.png) !important;
}
```
Or change .card from background to background-color.

Oh yeah, there is also this:
```
.tag-container, .tag-container .tag-topic-count
{
    border-color: var(--main-background) !important;
}

pre
{
    color: var(--dimer-text) !important;
}
```

@tkosamja Add these to the code. Maybe see if anything else needs fixing THEN do a pull.

**Comment by tkosamja** [comment]
@DecentM would it be possible to fix this so the code doesn't get deformed?

![screenshot from 2018-02-04 15-49-07](https://user-images.githubusercontent.com/26143003/35779330-2d3b6ea4-09c3-11e8-820a-da971a207a37.png)

**Comment by RaitaroH** [comment]
Looks like this to me:
![image](https://user-images.githubusercontent.com/19552720/35779351-3693a9a6-09d4-11e8-812f-69bac96a7469.png)

**Comment by DecentM** [comment]
Oh, sorry. Groups aren't supposed to be on the navigation bar.
