### ISSUE TITLE
Forum needs rewrite

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/OpenUserCSS-DeepDark#15]
Also fix #14.

**Comment by RaitaroH** [comment]
@tkosamja so yeah, pretty tight with college so this would have to wait for a long time for sure. Too much for my taste. But yeah, just too much on my plate. If you have some time man. ALSO PLEASE update your fork first or make another one. Feel free to delete anything from the forum code. Most of it might be useless (the svg's are fine I think, the notif are fine too, some other crap idk).

Otherwise idk, wait I guess.

**Comment by RaitaroH** [comment]
@tkosamja @DecentM So in case tk doens't have time (also weird name man, glad I have autofill) should I just remove the forum code for now and update that so the forum at least looks less broken or should I just have it there. Alternatively I could code it as an option in stylus and call it `ALFA` or something. 

Your thoughts.

**Comment by DecentM** [comment]
I don't think it's necessary to delete the theme if that's what you're talking about. I think it's enough if you add a note in the description.  
If you really want to make a prominent notice, you can put a simple bar at the top like this: https://openusercss.org/theme/5a2f819f7c57c751001b49df/%7B%22viewingSource%22%3Atrue%7D  

You can also split the theme up to a forum one and a main one to limit the damage (I think you mean this).

**Comment by RaitaroH** [comment]
Ey, @the-j0k3r if you want to take a jab at this too... be my quest. I have themed "mostly" everything myself. Right now there a LOT of small little issues eveywhere :man_facepalming:

**Comment by RaitaroH** [comment]
@DecentM Nice too see now this theme is working for the forum again :stuck_out_tongue:

**Comment by RaitaroH** [comment]
Some stuff to have in mind:
- ~~undelete button in the chat~~
- ~~this ugly white border in the delete confirmation~~
- ~~this horrible underline for timestamps~~
- ~~tags (see posts)~~
- ...

**Comment by the-j0k3r** [comment]
> Ey, @the-j0k3r if you want to take a jab at this too... be my quest. I have themed "mostly" everything myself. Right now there a LOT of small little issues eveywhere man_facepalming

You mean fix your style for openuserCSS?

If so, maybe, IDK I dont use the site, BUT if I were to use it, if there are admin/mod portions and I have no access then I cant style/fix anything there, and I hate leaving crap behind. Similar to my USO dark theme and their admin/mod portions that are unstyled.

**Comment by RaitaroH** [comment]
@the-j0k3r no problem. I thought you also hosted your themes there.

**Comment by the-j0k3r** [comment]
I dont at this moment the only userCSS I have https://github.com/style-it-themes/travis-ci-inspired-dark-extended is nearly 500Kb big and too big for USO, if openuserCSS accommodates that I may change my mind.

But again without admin access and styling blindly will be crap.

**Comment by RaitaroH** [comment]
> But again without admin access and styling blindly will be crap.

Admin rights? Yo @DecentM give me brag... admin rights. XD

**Comment by the-j0k3r** [comment]
Ive already fixed your botched job of the patreon image

**Comment by RaitaroH** [comment]
@the-j0k3r  `botched`? Seriously? Why should I bother when it works with a filter?

Like seriously? Who cares besides you anyway? XD I know the feeling but there is no point to go in such detail when a simple fix does the job anyway :wink:

**Comment by the-j0k3r** [comment]
boched, I used a filter too.

![capture](https://user-images.githubusercontent.com/31389848/41114515-919c662c-6a7c-11e8-95c4-430f356ac54a.PNG)

yours is the top one, botched hahahaha.

**Comment by RaitaroH** [comment]
XD I didn't even noticed the cut off. It looks fine from the distance. Do a pull.

**Comment by the-j0k3r** [comment]
Ill do more fixes Im sure you went lazy in other parts and see...

**Comment by RaitaroH** [comment]
> Ill do more fixes Im sure you went lazy in other parts and see...

low blow, particularly now that its broken. also damn that logo, i never noticed

**Comment by RaitaroH** [comment]
@DecentM says it's flawless XD. I would say there are more things to be done, joker would say at least 1000 extra lines are needed.

https://forums.openusercss.org/topic/10/openusercss-deepdark/4

**Comment by the-j0k3r** [comment]
hahahaha dont make me pee my pants.

**Comment by the-j0k3r** [comment]
@RaitaroH thax for the invite to join, however I must decline for privacy reasons.

a) Im not giving out my mobile phone number to GitHub (Microsoft) or any other company for that matter.
b) Im not installing 3rd party spyware apps on my phone to enable 2factor nonsense.

So unless the restricttion of 2fa are laxed I wont be joining thank you and sorry.

My password for GtHub is not 1234 either, thats not how it goes here. :)

**Comment by DecentM** [comment]
I'm not sure if I'm the dumb one here, but I can't see GitHub asking for phone numbers anywhere. I don't think there is an option to, even if I wanted to link my phone.

Everyone in the org has access to the OUC build stack (internal logs, etc), and I'll expand this for easier development later, so unfortunately 2fa has to stay. There are plenty of open source apps for this, including Authenticator (it supports TOTP, which is what almost all sites use): https://f-droid.org/packages/net.bierbaumer.otp_authenticator/

**Comment by the-j0k3r** [comment]
To setup 2fa its via sms or download app on phone

![capture](https://user-images.githubusercontent.com/31389848/41117723-c05c8c22-6a85-11e8-8522-00e081404cf2.PNG)

@DecentM  I understand your position, but from my side I wont sacrifice privacy and I dont truest their security with my personal data, Maybe if I get some cheap throw away, Ill reconsider.

**Comment by RaitaroH** [comment]
@DecentM Actually I hate the token I need to use... is a huge pain. I would also like to remove the 2fa.

**Comment by DecentM** [comment]
Since the site handles e-mail addresses, disabling 2fa would be a breach of the GDPR because of the member access I mentioned before.  
I have been looking into moving to GitLab though. So far it looks great, so maybe I'll move the main repo there, then I'll be able to disable 2fa on this org.

**Comment by the-j0k3r** [comment]
Well IDK how youre setup or why you moving to Gitlab would solve the 2fa, seems like theres are portions of your setup that youre sharing and cant setup permission for, that could have been solved here too, but I guess now MS owns GitHub everyone is skittish., Anyway doesnt much matter.

GDPR requires 2fa? Seriously? If this is true then they dont read tech security news at all.

**Comment by RaitaroH** [comment]
This issue should be closed. The forum them is workable now.

**Comment by the-j0k3r** [comment]
Good :)

**Comment by DecentM** [comment]
> GDPR requires 2fa? Seriously? If this is true then they dont read tech security news at all.  

As far as I know, it doesn't mandate using specific technologies, but rather seeks to ensure that people's private information is protected well. Since I've previously set up federated authentication with GH on the build server, it'd be really unwise to lower security there.  

Moving to GitLab will be better, since they have their own build setup, integrated into the platform. Then I can turn off 2fa here.

**Comment by the-j0k3r** [comment]
>> Like seriously? Who cares besides you anyway? XD I know the feeling but there is no point to go in such detail when a simple fix does the job anyway wink

@RaitaroH https://www.patreon.com/brand/guidelines Patreon cares :)

The reason why I post this, is only so you are informed in case you werent aware.

IMO these guidelines are to be respected.

Solution 1: Its better to pull their logo and host it on the repo and link the background image, one method is described here https://www.sitepoint.com/why-hosting-your-svgs-is-hard-and-how-to-beat-it/ using GitHub, not necessarily gists but in the theme repo directly.

Soution 2: dont style those portions :)

Personally I would want to avoid any possibility of some unpleasant email, even if it is unlikely.

**Comment by the-j0k3r** [comment]
Also, I already have some working fixes for v1.0.0 of the website which should be out today sometime.

https://forums.openusercss.org/topic/32/1-0-0-release

https://forums.openusercss.org/topic/26/staging-area
