### ISSUE TITLE
commit d021dc9

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/OpenUserCSS-DeepDark#29]
@the-j0k3r 

Remember what this was for?
```
	/* this styles the bio preview pane below and the theme submission preview pane
	Im taking inspiration from the post submission preview well
	commit d021dc9 or https://git.io/vhKn1 */
	.columns > div > div > div:nth-child(4), .box.is-minheight-description
	{
		background: var(--main-background) !important;
		color: var(--main-text) !important;
		opacity: .75;
	}
```

Because I will have to delete it due to:
![screenshot_20180804_164243](https://user-images.githubusercontent.com/19552720/43677121-6b295002-9805-11e8-829a-c5cb05d4b040.png)

**Comment by the-j0k3r** [comment]
Yes it says it on the comment its pretty clear.

You can do whatever you like to this, so if it breaks something else that it was intended to fix so be it (an it will break post  preview well which was  d021dc9 ). or https://github.com/OpenUserCSS/OpenUserCSS-DeepDark/commit/d021dc9b37bbe1b3b3a36973c4e815bb42691003

If I were you I would find a specific selector to fix whatever youre looking at, but tbh I dont really care

If you are talking about 
```
.columns > div > div > div:nth-child(4), .box.is-minheight-description
	{
		background: var(--main-background) !important;
		color: var(--main-text) !important;
		opacity: .75;
	}
```
that is for /* this styles the bio preview pane below and the theme submission preview pane */
AKA user profile bio preview pane. and style submission preview pane

Im no longer using the site or doing updates to this style or getting involved with anything OpenUserCSS.

**Comment by RaitaroH** [comment]
k, thx

**Comment by the-j0k3r** [comment]
Youre welcome.

Im in openstyles stylus discord channels if you want to chat.
