### ISSUE TITLE
Don't use component IDs

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/OpenUserCSS-DeepDark#3]
Using the component IDs (the data-v-##### selectors) carries a hidden, backstabbing thorn, because they are automatically generated.
So at some point, the theme will break, because the components will get a different ID and you'll be left pondering why pretty much everything is "unthemed" :construction_worker:.

I put classes into the HTML that start with `.ouc-` specifically for making theme writing for the site easier. If you can, please start switching over to them wherever possible.
If there are classes missing, I'd be happy to add them as needed!

**Comment by RaitaroH** [comment]
Ah, damn.

**Comment by RaitaroH** [comment]
@DecentM I will use this to point out stuff I need from you.
I cannot find a more proper selector for this:
`.navbar-item[data-v-69502204]:not(.no-active):not(.router-link-exact-active):not(:hover)`
So just the links that aren't active in the navbar.

**Comment by DecentM** [comment]
> I will use this to point out stuff I need from you.

Sure, I'm watching the repo.
> I cannot find a more proper selector for this

Hmm, would `.navbar-item:not(.router-link-active)` work?

**Comment by RaitaroH** [comment]
`.navbar-item:not(.router-link-active)` no. I tried.

**Comment by DecentM** [comment]
I see now, this is a cascade priority issue. I'm updating the site to fix this as we speak.
After that this selector should work.

**Comment by RaitaroH** [comment]
Also, can you have separate selectors for h6 in boxes? I want to theme the by DecentM separetely.
I also can't theme this without using data.

**Comment by DecentM** [comment]
I can't really pick the username out without layout troubles, but I'll make sure to have more classes around cards.
Most of the time, component IDs don't change, so you can use the data tags wherever there's no other way. It would be really useful though, if you could create a list where you need classes and there are none, so I can add them at once, not per message.

If it works for you, just comment here where you need classes and let me know when you're done with the list so I can go over them.

**Comment by RaitaroH** [comment]
Oke, I will go through the entire theme. And I will tell you what I need at the end.

**Comment by RaitaroH** [comment]
https://github.com/OpenUserCSS/OpenUserCSS-DeepDark/commit/10e795437140d2d4562babeb882bb255d74734da
Nice huh? Almost everything is done, I will tell you what selectors I need. I have some problems with some buttons classes.

**Comment by RaitaroH** [comment]
Oh, the forum didn't have any data XD
Ok so here is what I need:

`.tile.is-child .button.is-primary` gets overwritten by `.content.is-marginless .button.is-primary, .level-left .button.is-primary`
That is `upload new theme` and `account` and also the buttons in the account settings get overwritten by `edit` and `install` theme buttons.


Can you tell me what are the selectors for code selection? #B5D5FF it has this color. I cannot find it.

**Comment by DecentM** [comment]
Thanks, I took note of where classes need to be.
I'm not sure what you mean by code selection, but all colour variables are exported to `:root`, you can check them out in your devtools inspector!

**Comment by RaitaroH** [comment]
![image](https://user-images.githubusercontent.com/19552720/34466890-683e9668-eeeb-11e7-99b3-4ef673df26c8.png)

This. I know it is somewhere but I ended up skipping it. I also themed the cursor.

**Comment by RaitaroH** [comment]
No, wait. I did theme this one before. You just changed the selector or something happened.
`.ace-tm .ace_marker-layer .ace_selection` is the new one. But damn I coulnd't find it XD
Sorry about that.

**Comment by DecentM** [comment]
Ah, yes. It's `.ace_selection`, with background-color.

**Comment by DecentM** [comment]
Probably the IDs changed, so just in time! 👍

**Comment by RaitaroH** [comment]
Ok, I fixed that too. 
Now if you could have those selectors for the buttons it would be amazing.

**Comment by DecentM** [comment]
Cross reference https://github.com/OpenUserCSS/openusercss.org/issues/35

**Comment by RaitaroH** [comment]
Finish this.
