### ISSUE TITLE
popover needs theming

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/OpenUserCSS-DeepDark#4]
@DecentM Help me out to get this popover element to not disappear. Such elements are really hard to theme, but yours really gets on my nerves XD
```
*, *:before, *:after {
transition-property: none !important;
transform: none !important;
animation: none !important;
visibility: visible !important;
display: block !important;
}
```

~~`#vomnibar` Also needs theming. I will have to add some url or regexp for the iframe (though even if I theme an iframe with stylus it is still not themed, even if it is on the same domain, for some reason)
Also what is this vomnibar thing? I got it by using the code above. I have no idea how to trigger it.~~

**Comment by RaitaroH** [comment]
@DecentM I themed the profile stats.

I still don't know what the vomnibar is, but stylus shows this:
```
Stylus doesn't work on pages like this.

As a security precaution­, the browser prohibits extensions­ from affecting its built-in pages (like chrome://version, the standard new tab page as of Chrome 61, about:addons, and so on) as well as other extensions­' pages. Each browser also restricts access to its own extensions­ gallery (like Chrome Web Store or AMO).
```

**Comment by DecentM** [comment]
Nice job!
Not sure where that element comes from. Can you see if it's inserted by an extension? That message only pops up on internal pages.

**Comment by RaitaroH** [comment]
Ah... wait. 
Yep my fault. Is an extension I have that ads vim. Sorry.
I shouldn't theme stuff when is really late... nor after I just woke up XD

Btw, I still didn't manage to make the element popover not hide itself. I had to chip at the css file.

**Comment by RaitaroH** [comment]
Some more theming needs to be done here. The other arrows and some 3 dots thing.
