### ISSUE TITLE
Remove box-shadow around avatars (transparent avatars problems) also notifications hover should make all the text blue

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/OpenUserCSS-DeepDark#6]

**Comment by tkosamja** [comment]
If I try in a fresh theme, `.notification-msg a:hover { color: var(--main-color) !important; }` works just fine. I guess other css it's stopping it from working the right way.

**Comment by RaitaroH** [comment]
That's how I fixed it. The strong wasn't theming itself so I had a special rule for it AND for the link, just to be safe.
